name: Markdown Autodocs

on:
  push

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          commit_author: Astat
          commit_message: 'docs: update readme'
          output_file_paths: '[./EXPORT.md]'
